### ISSUE TITLE
Questions about the pkl file

### ISSUE THREAD

**Issue by wym-dlone** [nasir6/rPPG#19]

**Comment by msreevani060** [comment]
While trying to run Run.py file throws error below :
init
<Figure size 640x480 with 2 Axes>
Traceback (most recent call last):
  File "/content/rPPG/run.py", line 65, in <module>
    runPOS(source)
  File "/content/rPPG/run.py", line 39, in __call__
    capture = CaptureFrames(self.batch_size, source, show_mask=True)
  File "/content/rPPG/capture_frames.py", line 20, in __init__
    self.model.load_state_dict(torch.load('/content/rPPG/linknet.pth'))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

As i could understand its pickle issue. Please let me know what to do and how to proceed?

**Comment by darcarper** [comment]
> Al intentar ejecutar el archivo Run.py, aparece el siguiente error: init
> 
> Rastreo (última llamada más reciente): Archivo "/content/rPPG/run.py", línea 65, en runPOS(fuente) Archivo "/content/rPPG/run.py", línea 39, en __call__ capture = CaptureFrames(self .batch_size, source, show_mask=True) Archivo "/content/rPPG/capture_frames.py", línea 20, en __init__ self.model.load_state_dict(torch.load('/content/rPPG/linknet.pth')) Archivo " /usr/local/lib/python3.7/dist-packages/torch/serialization.py", línea 608, en el retorno de carga _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) Archivo "/usr/local/lib/python3 .7/dist-packages/torch/serialization.py", línea 777, en _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: clave de carga no válida, 'v'.
> Como pude entender su problema de salmuera. Por favor, hágame saber qué hacer y cómo proceder.

have you been able to solve?
