### ISSUE TITLE
Error - "_pickle.UnpicklingError: invalid load key"

### ISSUE THREAD

**Issue by mendes-davi** [nasir6/rPPG#2]
I got the following error message while running the program. Also, 'linknet.pth' is present the folder. 
PS: I'm not using a CUDA enabled device and i tried to use `map_location='cpu'` argument in `torch.load` function.

Thanks!
Davi

```bash
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    runPOS(source)
  File "run.py", line 39, in __call__
    capture = CaptureFrames(self.batch_size, source, show_mask=True)
  File "/home/davi/Dropbox/rPPG/nasir6_rPPG/capture_frames.py", line 20, in __init__
    self.model.load_state_dict(torch.load('linknet.pth'))
  File "/home/davi/.cv/OpenCV-3.4-py3/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/davi/.cv/OpenCV-3.4-py3/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by nasir6** [comment]
Please try to download linknet.pth from google drive https://drive.google.com/open?id=1shRnrUAF5HyA_vwXJfCcrNVFkltT7U5E and see if the issue still persists?

**Comment by mendes-davi** [comment]
Thanks! Problem solved
